# Project identification
sonar.projectKey=nema17-python
sonar.projectName=nema17-python

# Source code location
sonar.sources=.

# Encoding of the source files
sonar.sourceEncoding=UTF-8

# SonarQube server URL
sonar.host.url=http://localhost:9000
